### ISSUE TITLE
[MINVOKER-31] Test failing because of system property

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-invoker-plugin#305]
**[Paul Gier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pgier)** opened **[MINVOKER-31](https://issues.apache.org/jira/browse/MINVOKER-31?redirect=false)** and commented

I'm getting a test failure like the following when I try to build the invoker plugin:

testSimpleRunValidate(org.apache.maven.plugin.invoker.InvokerMojoTest)  Time elapsed: 0.139 sec  <<< ERROR!
java.lang.IllegalStateException: Maven application directory was not specified, and ${maven.home} is not provided in the system properties. Please specify at least on of these.
at org.apache.maven.shared.invoker.MavenCommandLineBuilder.checkRequiredState(MavenCommandLineBuilder.java:119)
at org.apache.maven.shared.invoker.MavenCommandLineBuilder.build(MavenCommandLineBuilder.java:58)

I tried setting "maven.home" from the command line, but it still gave the same error.  For some reason the properties are not being passed to the junit tests.

Upgrading the version of surefire to 2.4.2 seems to fix the problem.

---

**Attachments:**
- [MINVOKER-31-surefire-update.patch](https://issues.apache.org/jira/secure/attachment/12716652/MINVOKER-31-surefire-update.patch) (_398 bytes_)

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed in rev 649291.
Thanks.
