### ISSUE TITLE
[MINVOKER-8] invoker unit tests fail

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-invoker-plugin#314]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MINVOKER-8](https://issues.apache.org/jira/browse/MINVOKER-8?redirect=false)** and commented

I get the following failure on my Mac:

testBuildShouldSucceed(org.apache.maven.shared.invoker.DefaultInvokerTest)  Time elapsed: 1.058 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<0> but was:<1>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at org.apache.maven.shared.invoker.DefaultInvokerTest.testBuildShouldSucceed(DefaultInvokerTest.java:44)
at org.apache.maven.shared.invoker.DefaultInvokerTest.testBuildShouldSucceed(DefaultInvokerTest.java:44)

The same issue is being seen in CI:
http://maven.zones.apache.org/continuum/surefireReport.action?buildId=13387&projectId=57#org.apache.maven.shared.invoker.DefaultInvokerTest

this is building the shared component.

---
No further details from [MINVOKER-8](https://issues.apache.org/jira/browse/MINVOKER-8?redirect=false)

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Looks ok now (build is fine on the ci server).
Reopen it if you have issues again.
