### ISSUE TITLE
[MINVOKER-18] two executions of the same pom causes a prooblem with interpolated-pom.xml

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-invoker-plugin#342]
**[Gerhard Langs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gerhard6)** opened **[MINVOKER-18](https://issues.apache.org/jira/browse/MINVOKER-18?redirect=false)** and commented

TestCase:
pom-interpolated2.xml uses invoker to invoke "pom-interpolated2-invoked.xml  in 2 "executions".

invocation:
mvn -f pom-interpolated2.xml test -e

the second execution fails, because it is unable to create the "interpolated-pom.xml".

Proposed solution:
- dont tag the interpolated-pom.xml as "deleteOnExit",
- delete that file at the end of every execution.

Will try to provide a patch....

Greetings, Gerhard

Output:
...
Caused by: org.apache.maven.plugin.MojoExecutionException: fail to create file D:\maven\maven-invoker-plugin\src\test\resources\unit\interpolation2\.\interpolated-pom.xml
at org.apache.maven.plugin.invoker.InvokerMojo.buildInterpolatedPomFile(InvokerMojo.java:997)
at org.apache.maven.plugin.invoker.InvokerMojo.runBuild(InvokerMojo.java:458)
at org.apache.maven.plugin.invoker.InvokerMojo.execute(InvokerMojo.java:341)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)

---

**Affects:** 1.1

**Attachments:**
- [invoker-18.patch](https://issues.apache.org/jira/secure/attachment/12716678/invoker-18.patch) (_1.50 kB_)
- [invoker-18.patch](https://issues.apache.org/jira/secure/attachment/12716660/invoker-18.patch) (_1.50 kB_)
- [pom-interpolation2.xml](https://issues.apache.org/jira/secure/attachment/12716686/pom-interpolation2.xml) (_1.67 kB_)
- [pom-interpolation2-invoked.xml](https://issues.apache.org/jira/secure/attachment/12716674/pom-interpolation2-invoked.xml) (_460 bytes_)

**Issue Links:**
- [MINVOKER-19](https://issues.apache.org/jira/browse/MINVOKER-19) two executions of the same pom causes a prooblem with interpolated-pom.xml
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Gerhard Langs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gerhard6)** commented

Provided a patch, which deletes the pom in the finally section

Aslo updated one of the existing tests, as the pom is not automatically deleted, when you only invoke buildInterpolationFromFile

Didn't add an automatic test for my testcase (=two attached pom's)

**Comment by jira-importer** [comment]
**[Gerhard Langs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gerhard6)** commented

...

**Comment by jira-importer** [comment]
**[Gerhard Langs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gerhard6)** commented

One more note:
my proposed solution works, but has a small drawback: In some cases (eg. by interrupting a running process,) it can leave the interpolation file in place, and the next and all subsequent invocations then fail. So one more improvement would be either to also add the "deleteOnExit" flag or to always delete an old file before creating a new one

Gerhard.

**Comment by jira-importer** [comment]
**[Gerhard Langs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gerhard6)** commented

...

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

I have committed (rev 604529) the following fix for this issue.
Before created the interpolated pom file, if it already exists it will be deleted (I don't remove deleteOnExit).
Can you test with last deployed snapshot and reopen the issue if you have trouble ?
Thanks.

**Comment by jira-importer** [comment]
**[Gerhard Langs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gerhard6)** commented

Olivier
your fix works fine

Thanks, Gerhard

**Comment by jira-importer** [comment]
**[Gerhard Langs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gerhard6)** commented

...
