### ISSUE TITLE
[MINVOKER-87] Invoker install goal fails when used in eclipse

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-invoker-plugin#380]
**[Lee Thompson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stimpy)** opened **[MINVOKER-87](https://issues.apache.org/jira/browse/MINVOKER-87?redirect=false)** and commented

Using maven-invoker-plugin works great on the command line.

When used with eclipse, the install goal will fail to install a previous module's jar file into "localRepositoryPath".  A workaround is to use maven-install-plugin instead.

[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-invoker-plugin:1.3:install' -->
[DEBUG]   (f) localRepository = Repository[local|file:///Users/Lee/.m2/repository]
[DEBUG]   (f) localRepositoryPath = /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/target/it-repo
[DEBUG]   (f) project = MavenProject: org.codehaus.mojo:patch-maven-plugin:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/pom.xml
[DEBUG]   (f) reactorProjects = [MavenProject: org.codehaus.mojo:cbuild-parent:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/pom.xml, MavenProject: org.codehaus.mojo:cbuild-tool-parent:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/downloader/pom.xml, MavenProject: org.codehaus.mojo:cbuild-utils:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/cbuild-utils/pom.xml, MavenProject: org.codehaus.mojo:cbuild-plugin-parent:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/pom.xml, MavenProject: org.codehaus.mojo:cbuild-lifecycles:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/cbuild-lifecycles/pom.xml, MavenProject: org.codehaus.mojo:rpm-cbuild-maven-plugin:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/rpm-cbuild-maven-plugin/pom.xml, MavenProject: org.codehaus.mojo:patch-maven-plugin:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/pom.xml, MavenProject: org.codehaus.mojo:make-maven-plugin:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/make-maven-plugin/pom.xml, MavenProject: org.codehaus.mojo:shell-maven-plugin:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/shell-maven-plugin/pom.xml, MavenProject: org.codehaus.mojo:build-on-demand-maven-plugin:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/build-on-demand-maven-plugin/pom.xml]
[DEBUG]   - end configuration --
[INFO] [invoker:install {execution: integration-test}]
[DEBUG] On Install: Using artifact file for POM: org.codehaus.mojo:patch-maven-plugin:pom:1.0-beta-1-SNAPSHOT
[DEBUG] WARNING: Artifact: org.codehaus.mojo:patch-maven-plugin:pom:1.0-beta-1-SNAPSHOT does not have project-builder metadata (ProjectBuilderConfiguration) associated with it.
Cannot access CLI properties for version transformation.
[INFO] Installing /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/target/pom-transformed.xml to /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/target/it-repo/org/codehaus/mojo/patch-maven-plugin/1.0-beta-1-SNAPSHOT/patch-maven-plugin-1.0-beta-1-SNAPSHOT.pom
[INFO] Installing /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/target/patch-maven-plugin-1.0-beta-1-SNAPSHOT.jar to /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/target/it-repo/org/codehaus/mojo/patch-maven-plugin/1.0-beta-1-SNAPSHOT/patch-maven-plugin-1.0-beta-1-SNAPSHOT.jar
[DEBUG] On Install: Using artifact file for POM: org.codehaus.mojo:cbuild-plugin-parent:pom:1.0-beta-1-SNAPSHOT
[INFO] Installing /Users/Lee/Documents/workspace/c-builds/plugins/target/pom-transformed.xml to /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/target/it-repo/org/codehaus/mojo/cbuild-plugin-parent/1.0-beta-1-SNAPSHOT/cbuild-plugin-parent-1.0-beta-1-SNAPSHOT.pom
[DEBUG] On Install: Using artifact file for POM: org.codehaus.mojo:cbuild-parent:pom:1.0-beta-1-SNAPSHOT
[INFO] Installing /Users/Lee/Documents/workspace/c-builds/target/pom-transformed.xml to /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/target/it-repo/org/codehaus/mojo/cbuild-parent/1.0-beta-1-SNAPSHOT/cbuild-parent-1.0-beta-1-SNAPSHOT.pom
[DEBUG] On Install: Using artifact file for POM: org.codehaus.mojo:cbuild-utils:pom:1.0-beta-1-SNAPSHOT
[DEBUG] WARNING: Artifact: org.codehaus.mojo:cbuild-utils:pom:1.0-beta-1-SNAPSHOT does not have project-builder metadata (ProjectBuilderConfiguration) associated with it.
Cannot access CLI properties for version transformation.
[INFO] Installing /Users/Lee/Documents/workspace/c-builds/cbuild-utils/target/pom-transformed.xml to /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/target/it-repo/org/codehaus/mojo/cbuild-utils/1.0-beta-1-SNAPSHOT/cbuild-utils-1.0-beta-1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to install project dependencies: MavenProject: org.codehaus.mojo:patch-maven-plugin:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/pom.xml

Embedded error: Failed to install project artifacts: MavenProject: org.codehaus.mojo:cbuild-utils:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/cbuild-utils/pom.xml
Artifact is not fully assembled: /Users/Lee/Documents/workspace/c-builds/cbuild-utils/target/classes
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to install project dependencies: MavenProject: org.codehaus.mojo:patch-maven-plugin:1.0-beta-1-SNAPSHOT @ /Users/Lee/Documents/workspace/c-builds/plugins/patch-maven-plugin/pom.xml
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:703)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)

---

**Affects:** 1.3

**Issue Links:**
- [MNG-3085](https://issues.apache.org/jira/browse/MNG-3085) mvn script isn't setting maven.home correctly with cygwin on xp

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> Artifact is not fully assembled: /Users/Lee/Documents/workspace/c-builds/cbuild-utils/target/classes
> Well, what's the plugin supposed to install if there is no artifact? We could output a warning and skip the artifact, leaving the risk of the sub builds failing due to missing artifacts in the local repo, but apart from this I don't see much choice.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

There's an option named [Resolve workspace artifacts](http://docs.codehaus.org/display/MAVEN/Running+and+debugging+Maven+2.1+from+m2e+workspace) in M2Eclipse. For Maven launch configurations that go beyond `package` phase, that should be disabled to restore Maven's original dependency resolution. See also [MNGECLIPSE-1134](https://issues.sonatype.org/browse/MNGECLIPSE-1134).
