### ISSUE TITLE
[MINVOKER-159] install-goal should use same mavenHome as run-goal

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-invoker-plugin#455]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** opened **[MINVOKER-159](https://issues.apache.org/jira/browse/MINVOKER-159?redirect=false)** and commented

When running the build with M3, and the invoker with M2.0.6 as mavenHome, you get an exception like

```
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to read local copy of metadata: Cannot read metadata from 'E:\java-workspace\apache-maven-plugins\maven-deploy-plugin\target\local-repo\org\apache\maven\plugins\maven-deploy-plugin\2.9-SNAPSHOT\maven-metadata-local.xml': expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<extension>jar</... @13:25) 
  org.apache.maven.plugins:maven-deploy-plugin:pom:2.9-SNAPSHOT


	at org.apache.maven.artifact.transform.SnapshotTransformation.transformForResolve(SnapshotTransformation.java:68)
	at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForResolve(DefaultArtifactTransformationManager.java:57)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:114)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:73)
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:526)
	... 19 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataResolutionException: Unable to read local copy of metadata: Cannot read metadata from 'E:\java-workspace\apache-maven-plugins\maven-deploy-plugin\target\local-repo\org\apache\maven\plugins\maven-deploy-plugin\2.9-SNAPSHOT\maven-metadata-local.xml': expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<extension>jar</... @13:25) 
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolve(DefaultRepositoryMetadataManager.java:143)
	at org.apache.maven.artifact.transform.AbstractVersionTransformation.resolveVersion(AbstractVersionTransformation.java:65)
	at org.apache.maven.artifact.transform.SnapshotTransformation.transformForResolve(SnapshotTransformation.java:63)
	... 23 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataReadException: Cannot read metadata from 'E:\java-workspace\apache-maven-plugins\maven-deploy-plugin\target\local-repo\org\apache\maven\plugins\maven-deploy-plugin\2.9-SNAPSHOT\maven-metadata-local.xml': expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<extension>jar</... @13:25) 
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.readMetadata(DefaultRepositoryMetadataManager.java:292)
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.loadMetadata(DefaultRepositoryMetadataManager.java:244)
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.mergeMetadata(DefaultRepositoryMetadataManager.java:173)
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolve(DefaultRepositoryMetadataManager.java:134)
	... 25 more
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<extension>jar</... @13:25) 
	at org.codehaus.plexus.util.xml.pull.MXParser.nextTag(MXParser.java:1080)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.parseVersioning(MetadataXpp3Reader.java:513)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.parseMetadata(MetadataXpp3Reader.java:352)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:866)
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.readMetadata(DefaultRepositoryMetadataManager.java:279)
	... 28 more
```

Maven3 uses a different type of metadata, which is not forward-compatible. To solve this, the file should be installed with the target Maven version.

---

**Affects:** 1.8

**Issue Links:**
- [MSHADE-157](https://issues.apache.org/jira/browse/MSHADE-157) support relocate of role-hint
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

If we can choose the `ArtifactInstaller` matching the Maven version, then we can select the one which will also be used to invoke the projects.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

we are now using shared maven-artifact-transfer so no way to fix that
